-- Migration: 001_initial_schema.sql
-- Create all tables for gprint service

-- Customers: entities that contract services
CREATE TABLE customers (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(100) NOT NULL,
    
    -- Identification
    customer_code   VARCHAR2(50) NOT NULL,
    customer_type   VARCHAR2(20) DEFAULT 'INDIVIDUAL' CHECK (customer_type IN ('INDIVIDUAL', 'COMPANY')),
    
    -- Personal/Company Info
    name            VARCHAR2(255) NOT NULL,
    trade_name      VARCHAR2(255),
    tax_id          VARCHAR2(20),
    state_reg       VARCHAR2(30),
    municipal_reg   VARCHAR2(30),
    
    -- Contact
    email           VARCHAR2(255),
    phone           VARCHAR2(20),
    mobile          VARCHAR2(20),
    
    -- Address
    address_street  VARCHAR2(255),
    address_number  VARCHAR2(20),
    address_comp    VARCHAR2(100),
    address_district VARCHAR2(100),
    address_city    VARCHAR2(100),
    address_state   VARCHAR2(2),
    address_zip     VARCHAR2(10),
    address_country VARCHAR2(50) DEFAULT 'BR',
    
    -- Status & Metadata
    active          NUMBER(1) DEFAULT 1 CHECK (active IN (0,1)),
    notes           CLOB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR2(100),
    updated_by      VARCHAR2(100),
    
    CONSTRAINT uk_customer_tenant_code UNIQUE (tenant_id, customer_code),
    -- Composite unique constraint for tenant-aware foreign keys
    CONSTRAINT uk_customer_tenant_id UNIQUE (tenant_id, id)
);

CREATE INDEX idx_customers_tenant ON customers(tenant_id);
CREATE INDEX idx_customers_tax_id ON customers(tenant_id, tax_id);
CREATE INDEX idx_customers_name ON customers(tenant_id, UPPER(name));

-- Services: catalog of services offered (NOT goods)
CREATE TABLE services (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(100) NOT NULL,
    
    -- Identification
    service_code    VARCHAR2(50) NOT NULL,
    name            VARCHAR2(255) NOT NULL,
    description     CLOB,
    
    -- Classification
    category        VARCHAR2(100),
    subcategory     VARCHAR2(100),
    
    -- Pricing
    unit_price      NUMBER(15,2) NOT NULL,
    currency        VARCHAR2(3) DEFAULT 'BRL',
    price_unit      VARCHAR2(20) DEFAULT 'HOUR',
    
    -- Tax/Fiscal
    service_code_fiscal VARCHAR2(20),
    iss_rate        NUMBER(5,2) DEFAULT 0,
    irrf_rate       NUMBER(5,2) DEFAULT 0,
    pis_rate        NUMBER(5,2) DEFAULT 0,
    cofins_rate     NUMBER(5,2) DEFAULT 0,
    csll_rate       NUMBER(5,2) DEFAULT 0,
    
    -- Status
    active          NUMBER(1) DEFAULT 1 CHECK (active IN (0,1)),
    
    -- Metadata
    notes           CLOB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR2(100),
    updated_by      VARCHAR2(100),
    
    CONSTRAINT uk_service_tenant_code UNIQUE (tenant_id, service_code),
    -- Composite unique constraint for tenant-aware foreign keys
    CONSTRAINT uk_service_tenant_id UNIQUE (tenant_id, id)
);

CREATE INDEX idx_services_tenant ON services(tenant_id);
CREATE INDEX idx_services_category ON services(tenant_id, category);

-- Contracts: binding agreement between customer and services
CREATE TABLE contracts (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(100) NOT NULL,
    
    -- Identification
    contract_number VARCHAR2(50) NOT NULL,
    contract_type   VARCHAR2(30) DEFAULT 'SERVICE' CHECK (contract_type IN ('SERVICE', 'RECURRING', 'PROJECT')),
    
    -- Parties
    customer_id     NUMBER NOT NULL,
    
    -- Terms
    start_date      DATE NOT NULL,
    end_date        DATE,
    duration_months NUMBER(4),
    auto_renew      NUMBER(1) DEFAULT 0 CHECK (auto_renew IN (0,1)),
    
    -- Financial
    total_value     NUMBER(15,2),
    payment_terms   VARCHAR2(100),
    billing_cycle   VARCHAR2(20) DEFAULT 'MONTHLY',
    
    -- Status
    status          VARCHAR2(20) DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PENDING', 'ACTIVE', 'SUSPENDED', 'CANCELLED', 'COMPLETED')),
    signed_at       TIMESTAMP,
    signed_by       VARCHAR2(100),
    
    -- Document
    document_path   VARCHAR2(500),
    document_hash   VARCHAR2(128),
    
    -- Metadata
    notes           CLOB,
    terms_conditions CLOB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR2(100),
    updated_by      VARCHAR2(100),
    
    CONSTRAINT uk_contract_tenant_number UNIQUE (tenant_id, contract_number),
    -- Composite unique constraint for tenant-aware foreign keys
    CONSTRAINT uk_contract_tenant_id UNIQUE (tenant_id, id),
    -- Tenant-aware foreign key to customers
    CONSTRAINT fk_contracts_customer FOREIGN KEY (tenant_id, customer_id)
        REFERENCES customers(tenant_id, id)
);

CREATE INDEX idx_contracts_tenant ON contracts(tenant_id);
CREATE INDEX idx_contracts_customer ON contracts(tenant_id, customer_id);
CREATE INDEX idx_contracts_status ON contracts(tenant_id, status);
CREATE INDEX idx_contracts_dates ON contracts(tenant_id, start_date, end_date);

-- Contract Items: services included in a contract
CREATE TABLE contract_items (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(100) NOT NULL,
    
    contract_id     NUMBER NOT NULL,
    service_id      NUMBER NOT NULL,
    
    -- Pricing (can override service defaults)
    quantity        NUMBER(10,2) DEFAULT 1,
    unit_price      NUMBER(15,2) NOT NULL,
    discount_pct    NUMBER(5,2) DEFAULT 0 CHECK (discount_pct >= 0 AND discount_pct <= 100),
    line_total      NUMBER(15,2) GENERATED ALWAYS AS (quantity * unit_price * (1 - discount_pct/100)) VIRTUAL,
    
    -- Scheduling
    start_date      DATE,
    end_date        DATE,
    delivery_date   DATE,
    
    -- Description override
    description     CLOB,
    
    -- Status
    status          VARCHAR2(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    completed_at    TIMESTAMP,
    
    -- Metadata
    notes           CLOB,
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    -- Tenant-aware foreign keys
    CONSTRAINT fk_contract_items_contract FOREIGN KEY (tenant_id, contract_id)
        REFERENCES contracts(tenant_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_contract_items_service FOREIGN KEY (tenant_id, service_id)
        REFERENCES services(tenant_id, id)
);

CREATE INDEX idx_contract_items_contract ON contract_items(tenant_id, contract_id);
CREATE INDEX idx_contract_items_service ON contract_items(tenant_id, service_id);

-- Contract History: audit trail for contract changes
-- Note: contract_history uses RESTRICT (no cascade) to preserve audit trail
-- Contracts should use soft-delete (status='CANCELLED') instead of hard delete
CREATE TABLE contract_history (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(100) NOT NULL,
    
    contract_id     NUMBER NOT NULL,
    action          VARCHAR2(20) NOT NULL,
    field_changed   VARCHAR2(100),
    old_value       CLOB,
    new_value       CLOB,
    
    -- Actor
    performed_by    VARCHAR2(100) NOT NULL,
    performed_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address      VARCHAR2(50),
    user_agent      VARCHAR2(500),
    
    -- Tenant-aware foreign key (RESTRICT - preserve audit trail)
    CONSTRAINT fk_contract_history_contract FOREIGN KEY (tenant_id, contract_id)
        REFERENCES contracts(tenant_id, id)
);

-- Print jobs use CASCADE delete as they are disposable artifacts
CREATE TABLE contract_print_jobs (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR2(100) NOT NULL,
    
    contract_id     NUMBER NOT NULL,
    
    -- Job Status
    status          VARCHAR2(20) DEFAULT 'QUEUED' CHECK (status IN ('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED')),
    format          VARCHAR2(10) DEFAULT 'PDF' CHECK (format IN ('PDF', 'DOCX', 'HTML')),
    
    -- Output
    output_path     VARCHAR2(500),
    file_size       NUMBER,
    page_count      NUMBER,
    
    -- Timing
    queued_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at      TIMESTAMP,
    completed_at    TIMESTAMP,
    
    -- Error handling
    retry_count     NUMBER DEFAULT 0,
    error_message   CLOB,
    
    -- Metadata
    requested_by    VARCHAR2(100) NOT NULL,
    
    -- Tenant-aware foreign key (CASCADE - print jobs are disposable)
    CONSTRAINT fk_print_jobs_contract FOREIGN KEY (tenant_id, contract_id)
        REFERENCES contracts(tenant_id, id) ON DELETE CASCADE
);

CREATE INDEX idx_print_jobs_contract ON contract_print_jobs(tenant_id, contract_id);
CREATE INDEX idx_print_jobs_status ON contract_print_jobs(tenant_id, status);
-- Composite index for optimizing job queue queries: WHERE tenant_id = ? AND status = 'QUEUED' ORDER BY queued_at
CREATE INDEX idx_print_jobs_queue ON contract_print_jobs(tenant_id, status, queued_at);

-- Trigger to auto-update updated_at on customers
CREATE OR REPLACE TRIGGER trg_customers_updated_at
BEFORE UPDATE ON customers
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Trigger to auto-update updated_at on services
CREATE OR REPLACE TRIGGER trg_services_updated_at
BEFORE UPDATE ON services
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Trigger to auto-update updated_at on contracts
CREATE OR REPLACE TRIGGER trg_contracts_updated_at
BEFORE UPDATE ON contracts
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Trigger to auto-update updated_at on contract_items
CREATE OR REPLACE TRIGGER trg_contract_items_updated_at
BEFORE UPDATE ON contract_items
FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/
